name: Reporte BDD con Allure
on:
  push:
    branches:
      - main  

jobs:
  generate-report:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r proyecto/requirements.txt

      - name: Install Allure Behave formatter
        run: |
          pip install allure-behave

      - name: Install Allure Commandline
        run: |
          npm install -g allure-commandline --save-dev  # Instalar Allure Commandline

      - name: List project files for debugging
        run: |
          cd proyecto/Tests_BDD
          ls -R  # Verifica la estructura de directorios y archivos

      - name: Generate Allure results
        run: |
          cd proyecto/Tests_BDD
          behave -f allure_behave.formatter:AllureFormatter -o allure-results ./Features

      - name: Generate HTML report
        run: |
          cd proyecto/Tests_BDD
          allure generate allure-results --clean -o allure-report

      - name: Create Reports folder
        run: |
          mkdir -p ../Reportes  # Crear el directorio si no existe
          mv proyecto/Tests_BDD/allure-report/ ../Reportes/  # Mover el reporte HTML generado

      - name: Set up Git for deployment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy Reports folder to GitHub Pages
        run: |
          git fetch origin gh-pages || echo "No previous gh-pages branch"
          git checkout gh-pages || git checkout -b gh-pages
          git pull origin gh-pages || echo "No changes to pull from gh-pages"
          cp -r ../Reportes/* .  # Copia el contenido de la carpeta Reportes
          git add .  # Agrega todos los archivos copiados
          git commit -m "Deploy Allure report to gh-pages" || echo "No changes to commit"  # Manejo de caso si no hay cambios
          git push origin gh-pages  # Publica los cambios en la rama gh-pages