name: Semgrep Analysis

on: 
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies from requirements.txt (if applicable)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r proyecto/requirements.txt

      # Set up Semgrep with Docker
      - name: Set up Semgrep
        run: docker pull semgrep/semgrep

      # Run Semgrep Scan and produce SARIF report
      - name: Run Semgrep (SARIF Output)
        run: docker run --rm -v $(pwd):/src semgrep/semgrep semgrep scan --config="p/default" --sarif --output=report.sarif --metrics=off

      # Upload SARIF result to GitHub Code Scanning
      - name: Upload SARIF file to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif

      # Run Semgrep Scan and produce JSON report
      - name: Run Semgrep (JSON Output)
        run: docker run --rm -v $(pwd):/src semgrep/semgrep semgrep scan --config="p/default" --json --output semgrep.json --metrics=off

      # Install prospector-html for HTML report conversion
      - name: Install prospector-html
        run: python -m pip install prospector2html

      # Convert Semgrep JSON results to HTML
      - name: Convert Semgrep results to HTML
        run: prospector-html --input semgrep.json --output semgrep-report.html --filter semgrep || true

      # Create folder for reports if not exists
      - name: Move report to Reportes folder
        run: |
          mkdir -p Reportes  # Create directory if it doesn't exist
          mv semgrep-report.html Reportes/  # Move the HTML report to the Reportes folder

      # Publish report to GitHub Pages
      - name: Configure Git for GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Publish report to GitHub Pages
        run: |
          git fetch origin gh-pages  # Fetch the latest version of the gh-pages branch
          git checkout gh-pages  # Switch to the gh-pages branch
          cp Reportes/semgrep-report.html reporte-semgrep.html  # Rename while copying
          git add reporte-semgrep.html
          git commit -m "Publishing Semgrep report as reporte-semgrep.html" || echo "No changes to commit"  # Handle case if there are no changes
          git push origin gh-pages  # Push to GitHub Pages